config/routes.rb
Rails.application.routes.draw do


  get 'register', to: 'users#new', as: 'register'
  post 'register', to: 'users#create'
  get 'profile', to: 'users#show', as: 'profile'
  delete 'profile', to: 'users#destroy'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  patch 'profile/edit', to: 'users#update'
  get 'profile/apartments', to: 'users#apartments', as: 'user_apartments'
  post 'profile/apartments', to: 'users#add_apartment'

  root to: 'sessions#welcome'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  resources :apartments
  resources :neighborhoods, only: %i[index show] do
    collection do
      get 'search'
      get 'result'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/layout/_footer.erb
<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="two wide column">
        <a href="https://www.zillow.com" target="_blank">
          <img class="ui tiny centered image" src="/img/zillow-logo.png">
        </a>
      </div>
      <div class="two wide column">
        <a href="https://opendata.cityofnewyork.us/" target="_blank">
          <img class="ui tiny centered image" src="/img/nyc-open-data-logo.png">
        </a>
      </div>
      <div class="eleven wide column">
        <h4 class="ui inverted header">
          NYC 311 Apartment Finder
        </h4>
        <p>
          By <a href="https://github.com/sachafrosell/" target="_blank">Alex Frosell</a> and <a href="https://github.com/ihollander/" target="blank">Ian Hollander</a>. Data provided by Zillow API and NYC Open Data API.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/layout/_header.erb
<div id="top-nav-bar" class="ui inverted vertical center aligned segment">
  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <%= link_to neighborhoods_path, class: "header item" do %>
        NYC<i class="small red heart icon" style="margin: 0;"></i>311 Apartment Finder
      <% end %>
      <%= link_to apartments_path, class: "item" do %>
        <i class="building icon"></i>
        Apartments
      <% end %>
      <%= link_to neighborhoods_path, class: "item" do %>
        <i class="map icon"></i>
        Neighborhoods
      <% end %>
      <div class="ui simple dropdown right item">
        <i class="user circle icon large"></i>
        <i class="dropdown icon"></i>
        <div class="left menu">
          <%= link_to 'My Profile', edit_profile_path, class: "item" %>
          <%= link_to user_apartments_path, class: "item" do %>
            Saved Apartments
            <div class="ui teal label" style="margin-left: 3px;"><%= @user.apartments.count %></div>
          <% end %>
          <%= link_to 'Log Out', logout_path, method: :delete, class: "item" %>
        </div>
      </div>
    </div>
  </div>
</div>