config/routes.rb
Rails.application.routes.draw do


  get 'register', to: 'users#new', as: 'register'
  post 'register', to: 'users#create'
  get 'profile', to: 'users#show', as: 'profile'
  delete 'profile', to: 'users#destroy'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  patch 'profile/edit', to: 'users#update'
  get 'profile/apartments', to: 'users#apartments', as: 'user_apartments'
  post 'profile/apartments', to: 'users#add_apartment'

  root to: 'sessions#welcome'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  resources :apartments
  resources :neighborhoods, only: %i[index show] do
    collection do
      get 'search'
      get 'result'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :incidents
  has_many :searches
  has_many :users, through: :searches
  has_many :apartments
  has_many :journeys_a, class_name: "Journey", foreign_key: "neighborhood_a_id"
  has_many :journeys_b, class_name: "Journey", foreign_key: "neighborhood_b_id"
  has_many :apartments

  scope :find_by_lonlat, -> (longitude, latitude) {
    where(%{
      ST_Within(ST_SetSRID(ST_MakePoint(%f, %f),4326), geom)
    } % [longitude, latitude])
  }

  def name_with_borough
    "#{self.borough} | #{self.name}"
  end

  def commute_time(origin_neighborhood_id)
    journey = Journey.find_by(neighborhood_a_id: self.id, neighborhood_b_id: origin_neighborhood_id) || Journey.find_by(neighborhood_b_id: self.id, neighborhood_a_id: origin_neighborhood_id)
    journey.transit_trip_duration / 60
  end

  def self.find_by_address(address)
    api_client = GoogleApi::MapsClient.new
    json_response = api_client.geocode(address)
    # get lat and long as floats
    lat = json_response["results"][0]["geometry"]["location"]["lat"]
    lng = json_response["results"][0]["geometry"]["location"]["lng"]
    self.find_by_lonlat(lng, lat).first
  end

  def center_latitude
    self.geom.centroid.y
  end

  def center_longitude
    self.geom.centroid.x
  end

  def center_latitude_longitude_string
    "#{self.center_latitude},#{self.center_longitude}"
  end

  def random_zip
    self.incidents.count > 0 ? self.incidents.sample.zip : nil
  end

  # read geojson string and add properties for heatmap
  def geojson
    "/geojson/neighborhood_id_#{self.id}.json"
  end

  def static_map_url
    base_url = "https://maps.googleapis.com/maps/api/staticmap?"
    enc = Polylines::Encoder.encode_points(self.geom_array)
    params = {
      center: center_latitude_longitude_string,
      zoom: "13",
      size: "300x300",
      key: Rails.application.credentials.google[:api_key]
    }
    base_url + params.to_query + '&path=fillcolor:0xAA000033%7Ccolor:0xFFFFFF00%7Cenc:' + enc
  end

  # converts geom multipolygon to array of lat long points
  def geom_array
    factory = RGeo::GeoJSON::EntityFactory.instance
    feature = factory.feature self.geom
    hash = RGeo::GeoJSON.encode feature
    hash["geometry"]["coordinates"][0][0]
  end

  def find_street
    new_params = []
    incidents = self.incidents.where("incidents.incident_address is not null")
    incident = incidents.sample
    address = incident.incident_address
    zip = incident.zip
    new_params.push(address, zip)
    new_params
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_criteria_options, only: :index
  before_action :current_user, only: [:index, :result]

  # starting page for filtering distance
  def index
    neighborhood_ids = Journey.within_acceptable_duration(@user.neighborhood_id, @user.commute_time).map(&:neighborhood_b_id)
    neighborhood_ids += Journey.within_acceptable_duration_reverse(@user.neighborhood_id, @user.commute_time).map(&:neighborhood_a_id)
    if neighborhood_ids.count > 0 then
      @neighborhoods = Neighborhood.find(neighborhood_ids).uniq
      @neighborhoods.sort_by! { |n| n.name_with_borough }
    else
      flash[:error] = "No routes match"
    end
  end

  def show
    @neighborhood = Neighborhood.find_by(id: params[:id])
    @complaint_types = Complaint.joins(:incidents).order("count_complaints_name DESC").where("neighborhood_id = ?", @neighborhood.id).select("complaints.name").group("complaints.name").count
  end

  # page for displaying results
  def result
    @criteria = params["search"]["criteria"].reject{ |n| n.empty? }
    neighborhood_ids = params["search"]["neighborhoods"].reject{ |n| n.empty? }
    if @criteria.count < 3 || neighborhood_ids.count < 3
      flash[:errors] = ["Please select at least three neighborhoods and three criteria."]
      redirect_to neighborhoods_path
    else
      @neighborhoods = Neighborhood.find(neighborhood_ids)
      # sort by commute time
      @neighborhoods = @neighborhoods.sort_by do |n|
        n.commute_time(@user.neighborhood_id)
      end
      # this logic should be somewhere else... view model?
      @criteria_hash = {}
      @neighborhoods.each do |neighborhood|
        @criteria_hash["#{neighborhood.id}"] = {
          criteria: []
        }
        @criteria.each do |criteria|
          scope_method = Incident.criteria_hash[criteria.to_sym]["method"]
          incidents = neighborhood.incidents.send(scope_method)
          max_incidents = Incident.joins(:neighborhood).select("neighborhoods.name").send(scope_method).group("neighborhoods.name").count.max_by { |k,v| v }[1]
          incident_percentage = (1 - (incidents.count.to_f / max_incidents)) * 100
          @criteria_hash["#{neighborhood.id}"][:criteria] << {
            name: criteria,
            alias: Incident.criteria_hash[criteria.to_sym]["show_alias"],
            incidents: incidents.count,
            max_incidents: max_incidents,
            incident_percentage: incident_percentage
          }
        end
        percentages = @criteria_hash["#{neighborhood.id}"][:criteria].collect{ |p| p[:incident_percentage] }
        match_percentage = (percentages.reduce(:+) / percentages.count).to_i
        @criteria_hash["#{neighborhood.id}"][:match_percentage] = match_percentage
      end
    end
  end

  private

  def set_criteria_options
    @criteria_options = Incident.criteria_hash.keys.sort
  end

end

app/views/neighborhoods/_map.erb
<div id="mapDiv" style="height: 500px;"></div>
<script type="text/javascript">
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('mapDiv'), {
      zoom: 12,
      center: new google.maps.LatLng(40.712776, -74.005974), //change to center on user address?
      mapTypeId: 'terrain',
      styles: [
          {
              "featureType": "water",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#e9e9e9"
                  },
                  {
                      "lightness": 17
                  }
              ]
          },
          {
              "featureType": "landscape",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#f5f5f5"
                  },
                  {
                      "lightness": 20
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "geometry.fill",
              "stylers": [
                  {
                      "color": "#ffffff"
                  },
                  {
                      "lightness": 17
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "geometry.stroke",
              "stylers": [
                  {
                      "color": "#ffffff"
                  },
                  {
                      "lightness": 29
                  },
                  {
                      "weight": 0.2
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#ffffff"
                  },
                  {
                      "lightness": 18
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#ffffff"
                  },
                  {
                      "lightness": 16
                  }
              ]
          },
          {
              "featureType": "poi",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#f5f5f5"
                  },
                  {
                      "lightness": 21
                  }
              ]
          },
          {
              "featureType": "poi.park",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#dedede"
                  },
                  {
                      "lightness": 21
                  }
              ]
          },
          {
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "visibility": "on"
                  },
                  {
                      "color": "#ffffff"
                  },
                  {
                      "lightness": 16
                  }
              ]
          },
          {
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "saturation": 36
                  },
                  {
                      "color": "#333333"
                  },
                  {
                      "lightness": 40
                  }
              ]
          },
          {
              "elementType": "labels.icon",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "featureType": "transit",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#f2f2f2"
                  },
                  {
                      "lightness": 19
                  }
              ]
          },
          {
              "featureType": "administrative",
              "elementType": "geometry.fill",
              "stylers": [
                  {
                      "color": "#fefefe"
                  },
                  {
                      "lightness": 20
                  }
              ]
          },
          {
              "featureType": "administrative",
              "elementType": "geometry.stroke",
              "stylers": [
                  {
                      "color": "#fefefe"
                  },
                  {
                      "lightness": 17
                  },
                  {
                      "weight": 1.2
                  }
              ]
          }
      ]
    });
    <% neighborhoods.each do |neighborhood| %>
      map.data.loadGeoJson("<%= neighborhood.geojson %>");
      //styling: find id from geojson and match...
    <% end %>
  }
</script>

<script
  async
  defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:ian_api_key] %>&callback=initMap">
</script>

app/views/neighborhoods/index.erb
<div class="ui grid">
  <div class="ten wide column">
    <h2 class="ui header">
      Neighborhood Info
    </h2>
    <p>
      We've found <%= @neighborhoods.count %> neighborhoods within <%= @user.commute_time %> minutes 
      of your work address, <strong><%= @user.work_address %></strong>, via public transit.
    </p>
    <p>
      <%= link_to 'Edit your commuting preferences', edit_profile_path %> if you'd like to see other neighborhoods.
    </p>
    <div class="ui info message">
      <div class="header">
        Select Neighborhoods and Criteria
      </div>
      <p>
        What's important to you in a neighborhood? Select at least <strong>three criteria</strong> and <strong>three neighborhoods</strong> 
        from the options below in order to compare statistics from NYC 311 data.
      </p>
    </div>
    <%= form_tag result_neighborhoods_path, method: :get, class: "ui form fluid" do %>
      <div class="field">
        <%= label_tag "search[neighborhoods]", "Select neighborhoods:" %>
        <%= collection_select :search, :neighborhoods, @neighborhoods, :id, :name_with_borough, {}, { class: "ui fluid search dropdown", multiple: "" } %>
      </div>
      <div class="field">
        <%= label_tag "search[criteria]", "Select criteria:" %>
        <%= collection_select :search, :criteria, @criteria_options, :to_s, :to_s, {}, { class: "ui fluid search dropdown", multiple: "" } %>
      </div>
      <%= submit_tag "Search", class: "ui submit button" %>
    <% end %>
    <% if flash[:errors] %>
      <%= render partial: 'shared/form_errors', locals: {
        error_header: 'Search error',
        error_messages: flash[:errors]
      } %>
    <% end %>
  </div>
  <div class="six wide column">
    <%= render partial: 'map', locals: { neighborhoods: @neighborhoods } %>
  </div>
</div>

app/views/neighborhoods/result.erb
<h2 class="ui horizontal divider header">
  <i class="map icon"></i>
  Results
</h2>
<p>
  Here are your neighborhoods and the 311 incident information you 
  requested. Check the match percentage to see which neighborhoods most closely match your criteria.
</p>
<p>Displaying incident datas from <%= Incident.first_incident_date %> to <%= Incident.last_incident_date %>.</p>
<div class="ui divider"></div>
<div class="ui divided items">
  <% @neighborhoods.each do |neighborhood| %>
    <% match_percentage = @criteria_hash[neighborhood.id.to_s][:match_percentage] %>
    <div class="item">
      <div class="middle aligned image">
        <img src="<%= neighborhood.static_map_url %>">
      </div>
      <div class="content">
        <a class="header"><%= neighborhood.name %></a>
        <div class="meta">
          <div class="ui <%= match_percentage < 50 ? "red" : "green" %> label">
            <%= p "#{match_percentage} % overall match" %>
          </div>
          <div class="ui label">
            <i class="map outline icon"></i>
            <%= neighborhood.borough %>
          </div>
          <div class="ui label">
            <i class="clock outline icon"></i>
            <%= "#{neighborhood.commute_time(@user.neighborhood_id)} min. commute" %>
          </div>
        </div>
        <div class="description">
          <table class="ui compact very basic celled table">
            <thead>
              <tr>
                <th>Type</th>
                <th>Count</th>
                <th>Percent Match</th>
              </tr>
            </thead>
            <tbody>
              <% @criteria_hash[neighborhood.id.to_s][:criteria].each do |criteria| %>
                <tr>
                  <td class="eight wide column"><%= criteria[:alias] %></td>
                  <td><%= criteria[:incidents] %></td>
                  <td><%= number_to_percentage(criteria[:incident_percentage], precision: 0)  %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="extra">
          <%= link_to neighborhood, { class: "ui primary small button" } do %>
            <i class="circle info icon"></i>
            View Neighborhood Details
          <% end %>
          <%= link_to apartments_path(neighborhood: neighborhood.name), { class: "ui primary small button" } do %>
            View Apartments
            <i class="right chevron icon"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
<h2 class="ui horizontal divider header">
  <i class="bar chart icon"></i>
  311 Incident Comparison
</h2>
<p>
  Based on your criteria, here is a comparison of 311 incident reports for 
  each of your selected neighborhoods.
</p>
<div class="ui grid">
  <% @criteria.each do |criteria| %>
    <% scope_method = Incident.criteria_hash[criteria.to_sym]["method"] %>
    <% chart_data = Incident.joins(:neighborhood).select("neighborhoods.name").send(scope_method).where(neighborhood: @neighborhoods).group("neighborhoods.name").count %>
    <div class="eight wide column">
      <div class="ui center aligned segment">
        <h4><%= Incident.criteria_hash[criteria.to_sym]["show_alias"] %></h3>
        <%= column_chart chart_data  %>
      </div>
    </div>
  <% end %>
</div>

app/views/neighborhoods/show.erb
<h2><%= @neighborhood.name %> 311 Report</h2>
<p>Click an incident category below to view details on incident reports.</p>
<p>Displaying incidents from <%= Incident.first_incident_date %> to <%= Incident.last_incident_date %>.</p>
<div class="ui fluid styled accordion">
  <% @complaint_types.each do |complaint,count| %>
    <div class="title">
      <i class="dropdown icon"></i>
      <span class="ui red circular label" style="margin-right: 1em;"><%= count %></span><%= complaint %>
    </div>
    <div class="content">
      <table class="ui compact very basic celled table">
        <tbody>
          <% Incident.joins(:complaint).where("complaints.name = ? and incidents.neighborhood_id = ?", complaint, @neighborhood.id).each do |incident| %>
            <tr>
              <td class="four wide column"><%= incident.date_opened_string %></td>
              <td><%= incident.descriptor %></td>
              <td><%= incident.incident_address  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

<script>
  $(".ui.accordion").accordion();
</script>