config/routes.rb
Rails.application.routes.draw do


  get 'register', to: 'users#new', as: 'register'
  post 'register', to: 'users#create'
  get 'profile', to: 'users#show', as: 'profile'
  delete 'profile', to: 'users#destroy'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  patch 'profile/edit', to: 'users#update'
  get 'profile/apartments', to: 'users#apartments', as: 'user_apartments'
  post 'profile/apartments', to: 'users#add_apartment'

  root to: 'sessions#welcome'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  resources :apartments
  resources :neighborhoods, only: %i[index show] do
    collection do
      get 'search'
      get 'result'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
    belongs_to :neighborhood
    has_many :user_apartments, dependent: :destroy
    has_many :users, through: :user_apartments

    def self.seed
      Neighborhood.all.each do |neighborhood|
        seed_logic(neighborhood)
      end
      puts "completed seed"
      # test
    end

    def self.seed_logic(neighborhood)
      @neighborhood = Neighborhood.find_by(name: neighborhood.name)
      if Apartment.find_by(neighborhood_id: neighborhood.id) == nil
        puts "seeding #{neighborhood.name}"
        apartment = Apartment.find_or_create_from_api(neighborhood.name)

        if apartment == nil
          x = 0
          second_logic(neighborhood, x)
        end
      else
        puts "already have apartments for #{neighborhood.name}"
      end
    end

    def self.second_logic(neighborhood, x)
      # if Apartment.find_by(neighborhood_id: neighborhood.id) == nil
      if x < 9
        @client_communicator = ZillowApi::ListingClient.new
        address = neighborhood.find_street
        @listings = @client_communicator.get_listings(address[0], address[1])
        new_listings = third_logic(@listings, neighborhood, x)
        create_round_two(new_listings)
      end
    end

    def self.third_logic(listings, neighborhood, x)
      if listings["searchresults"]["message"]["code"] == "508"
        x += 1
        second_logic(neighborhood, x)
      else
        listings
      end
    end

    def self.create_round_two(listings)
      if listings["searchresults"]["message"]["code"] != "508" && listings["searchresults"]["message"]["code"] != "7"
        listings = listings["searchresults"]["response"]["results"]["result"]
        if listings.class == Array
          listings.each do |listing|
            apartment = Apartment.find_by(zillow_id: listing["zpid"])
            if !apartment
              create_apartment(listing)
            end
          end
        else
          apartment = Apartment.find_by(zillow_id: listings["zpid"])
          if !apartment
            create_apartment(listings)
          end
        end
      end
    end

    # def test
    #   Neighborhood.all.each do |neighborhood|
    #     if neighborhood.appartments.count < 10
    #       puts "re-seeding #{neighborhood}"
    #       Apartment.find_or_create_from_api(neighborhood)
    #     end
    #   end
    # end

    def self.find_or_create_from_api(neighborhood_name)
      response_hash = self.find_listings_in_neighborhood(neighborhood_name)
      if response_hash && response_hash["searchresults"]["message"]["code"] == "0"
        listing = response_hash["searchresults"]["response"]["results"]["result"]
        if listing.class == Array
          added = 0
          listing.each do |list|
            if added <= 5
              apartment = Apartment.find_by(zillow_id: list["zpid"])
              if !apartment
                create_apartment(list, neighborhood_name)
              end
            end
          end
          added += 1
        else
          apartment = Apartment.find_by(zillow_id: listing["zpid"])
          if !apartment
            Apartment.create_apartment(listing, neighborhood_name)
          end
        end
      end
    end

    def self.find_listings_in_neighborhood(name)
      @client_communicator = ZillowApi::ListingClient.new
      @array_of_zips = Incident.get_zips_from_neighborhoods(name)
      @array_of_zips.each do |zip|
        @listings = @client_communicator.get_listings(name, zip)
      end
      @listings
    end

    def add_image_and_description
      @second_communicator = ZillowApi::ListingClient.new
      hash = @second_communicator.get_listing_details(self.zillow_id)
      if pulic_data?(hash) && hash["updatedPropertyDetails"]["response"]["images"]
        if hash["updatedPropertyDetails"]["response"]["images"]
          # self.images = hash["updatedPropertyDetails"]["response"]["images"]["image"]["url"]
          if hash["updatedPropertyDetails"]["response"]["images"]["image"]["url"].class == Array
            hash["updatedPropertyDetails"]["response"]["images"]["image"]["url"].each do |url|
              if test_image_size(url)
                self.images << url
              end
            end
          end
          self.description = hash["updatedPropertyDetails"]["response"]["homeDescription"]
        end
      else
        self.images << "https://www.gumtree.com/static/1/resources/assets/rwd/images/orphans/a37b37d99e7cef805f354d47.noimage_thumbnail.png"
      end
    end

    def pulic_data?(hash)
      if hash["updatedPropertyDetails"]["message"]["code"] != "0"
        false
      else
        true
      end
    end

    def self.create_apartment(listing, neighborhood_name)
      @neighborhood = Neighborhood.find_by(name: neighborhood_name)
      listings_hash = {
        street: listing["address"]["street"],
        zipcode: listing["address"]["zipcode"],
        city: listing["address"]["city"],
        state: listing["address"]["state"],
        latitude: listing["address"]["latitude"],
        longitude: listing["address"]["longitude"],
        url: listing["links"]["homedetails"],
        value: listing["zestimate"]["amount"],
        price_change: listing["zestimate"]["oneWeekChange"]["deprecated"],
        zillow_id: listing["zpid"],
        sqft: listing["finishedSqFt"],
        bedrooms: listing["bedrooms"],
        bathrooms: listing["bathrooms"],
        year_built: listing["yearBuilt"],
        neighborhood_id: @neighborhood.id
      }

      apartment = Apartment.new(listings_hash)
      apartment.add_image_and_description

      if apartment.images.count != 0
        apartment.save
      end
    end

    def parse_value(value)
      "$#{value.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse}"
    end

    def test_image_size(url)
      answer = true
      if (FastImage.size(url)[1] * 1.332) >= FastImage.size(url)[0]
        answer = false
      end
      answer
    end

    def pluralize_bedroom(item)
      string = "Bedroom"
      if item != 1
        string = "Bedrooms"
      end
      string
    end

    def pluralize_bathroom(item)
      string = "Bathroom"
      if item != 1
        "Bathrooms"
      end
      string
    end

    def value?(value)
      !!value
    end

    def next
      self.class.where("id > ?", id).first
    end

    def previous
      self.class.where("id < ?", id).last
    end

  end # end of apartment class


    # def validation_logic(code, message)
    #   response_status = false
    #   if code == "508" || code == "507"
    #     "Error: no exact match found for input address"
    #   elsif code == "508" || code == "507"
    #     "Failed to resolve city/state (or zip code). message: #{message}"
    #   elsif code == "3" || code == "4" || code == "505"
    #     "The Zillow API is currently unavailable"
    #   elsif code == "1"
    #     "Service error: #{message}"
    #   elseif code == "2"
    #     "Invalid Zillow API key"
    #   elsif code == "0"
    #     "Request successfully processed"
    #     response_status = true
    #   end
    # end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :find_apartment, only: [:show, :save_apartment]

  def index
    @neighborhood = params["neighborhood"]
    @neighborhoods = Neighborhood.all.sort_by { |n| n.name_with_borough }
    if @neighborhood
      @apartments = Apartment.joins(:neighborhood).where(neighborhoods: { name: @neighborhood })
      if @apartments.count < 5
        Apartment.find_or_create_from_api(@neighborhood)
        @apartments = Apartment.joins(:neighborhood).where(neighborhoods: { name: @neighborhood })
      end
    else
      @apartments = Apartment.all
    end
  end

  def show
    @value = @apartment.value
    @street = @apartment.street
    @city = @apartment.city
    @state = @apartment.state
    @zipcode = @apartment.zipcode
    @sqft = @apartment.sqft
    @bedrooms = @apartment.bedrooms
    @bathrooms = @apartment.bathrooms
    @year_built = @apartment.year_built
    @images = @apartment.images
    @trending = @apartment.price_change
  end

  def save_apartment
    user_apartment = UserApartment.create(user_id: session[:user_id], apartment_id: @apartment.id)
  end

  private

  def find_apartment
    @apartment = Apartment.find_by(id: params[:id])
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_layout.erb
<div style="margin-top:25px">
  <div class="ui three column divided grid container">
    <div class="row">



      <div class="column" id="a-box" style="padding:40px" >
      <%= link_to @apartments.first do%>
        <p>
          <%= @apartments.first.street %>
          <br>
          <%= @apartments.first.city %>
          <br>
          <%= @apartments.first.state %>
          <br>
          <%= @apartments.first.zipcode %>
          <br>
          <%= @apartments.first.city %>
          <br>
          <%= "#{@apartments[0].bedrooms} Bed : #{@apartments[0].bathrooms} Bath : #{@apartments[0].sqft} sqft" %>
        </p>
      <% end %>
      </div>

      <div class="column" id="a-box" style="padding:40px">
        <p>
          <%= @apartments[1].street %>
          <br>
          <%= @apartments[1].city %>
          <br>
          <%= @apartments[1].state %>
          <br>
          <%= @apartments[1].zipcode %>
          <br>
          <%= @apartments[1].city %>
          <br>
          <%= "#{@apartments[1].bedrooms} Bed : #{@apartments[1].bathrooms} Bath : #{@apartments[1].sqft} sqft" %>
        </p>
      </div>
      <div class="column" id="a-box" style="padding:40px">
        <p>
          <%= @apartments[2].street %>
          <br>
          <%= @apartments[2].city %>
          <br>
          <%= @apartments[2].state %>
          <br>
          <%= @apartments[2].zipcode %>
          <br>
          <%= @apartments[2].city %>
          <br>
          <%= "#{@apartments[2].bedrooms} Bed : #{@apartments[2].bathrooms} Bath : #{@apartments[2].sqft} sqft" %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="column" id="a-box" style="padding:40px">
        <p>
          <%= @apartments[3].street %>
          <br>
          <%= @apartments[3].city %>
          <br>
          <%= @apartments[3].state %>
          <br>
          <%= @apartments[3].zipcode %>
          <br>
          <%= @apartments[3].city %>
          <br>
          <%= "#{@apartments[3].bedrooms} Bed : #{@apartments[3].bathrooms} Bath : #{@apartments[3].sqft} sqft" %>
        </p>
      </div>
      <div class="column" id="a-box" style="padding:40px">
        <p>
          <%= @apartments[4].street %>
          <br>
          <%= @apartments[4].city %>
          <br>
          <%= @apartments[4].state %>
          <br>
          <%= @apartments[4].zipcode %>
          <br>
          <%= @apartments[4].city %>
          <br>
          <%= "#{@apartments[4].bedrooms} Bed : #{@apartments[4].bathrooms} Bath : #{@apartments[4].sqft} sqft" %>
        </p>
      </div>
      <div class="column" id="a-box" style="padding:40px">
        <p>
          <%= @apartments[5].street %>
          <br>
          <%= @apartments[5].city %>
          <br>
          <%= @apartments[5].state %>
          <br>
          <%= @apartments[5].zipcode %>
          <br>
          <%= @apartments[5].city %>
          <br>
          <%= "#{@apartments[5].bedrooms} Bed : #{@apartments[5].bathrooms} Bath : #{@apartments[5].sqft} sqft" %>
        </p>
      </div>
    </div>
  </div>

app/views/apartments/index.erb
<!-- <div style="max-width: 600px;margin:0 auto;"> -->
<script>
  function goBack() {
    window.history.back()
  }
</script>
<h1>Results For <%= @neighborhood ? @neighborhood : "All Neighborhoods" %></h1>
<%= form_tag apartments_path, method: :get do %>
  <div class="ui grid">
    <div class="twelve wide column">
      <%= collection_select nil, :neighborhood, @neighborhoods, :name, :name_with_borough, {}, { class: "ui fluid search dropdown" } %>
    </div>
    <div class="four wide column">
      <%= submit_tag "Filter Apartments", class: "ui primary button" %>
    </div>
  </div>
<% end %>
<% if @apartments.count == 0 %>
  <br>
  <p>No results found for this neighborhood. Use the filter to select a different neighborhood.</p>
<% else %>
  <div class="ui items" style="padding-top:20px">
    <div class="ui grid" >
      <% @apartments.each do |apartment| %>
        <div class="eight wide column">
          <div class="item" style="padding:15px;background-color:#f8f8f9;border-radius:.28571429rem">
            <%= link_to apartment do %>
            <div class="ui right aligned grid">
              <div class="left floated right aligned six wide column">
                <div class="ui small image" >
                  <img src="<%= apartment.images.sample %>" style="max-height:110px">
                </div>
              </div>
                <div class="right floated left aligned ten wide column">
                  <div class="content" style="margin:14px">
                    <div class="header"><%= apartment.street %></div>
                    <div class="meta">
                      <span class="price"><%= apartment.city %></span>
                    </div>
                    <div class="meta">
                      <% if apartment.value %>
                      <span class="price" style="color:#9ACD32"><%= apartment.parse_value(apartment.value) %></span>
                      <% else %>
                      <span class="price">Price On Request</span>
                      <% end  %>
                    </div>
                    <div class="meta">
                      <span class="price"><%= "#{apartment.bedrooms} Bed : #{apartment.bathrooms} Bath : #{apartment.sqft} sqft" %></span>
                    </div>
                  </div>
                </div>
              </div>
            <% end  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

<button onclick="goBack()" class="ui primary button">Go back</button>

app/views/apartments/show.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


    <div>
      <% if @bedrooms != 0 %>
        <h1><%= "#{@bedrooms} Bedroom Apartment in #{@apartment.neighborhood.name}" %></h1>
      <% else %>
        <h1><%= "Slum in #{@apartment.neighborhood.name}" %></h1>
      <% end %>
    </div>
    <br>
    <% if @apartment.description %>
    <p><%= @apartment.description %></p>
    <% end %>
    <br>
    <div class="ui divider ">

    </div>

    <div class="ui grid container" style="margin-top:30px">
      <div class="eight wide column" style=";border-radius:.28571429rem;" id="apartment-grid" >
        <div class="flex-container">
          <table class="ui very basic celled table">
            <tbody>
              <tr>
                <td>Street</td>
                <td>
                  <%= "#{@street}," %>

                </td>
              </tr>
              <tr>
                <td>City</td>
                <td>

                  <%= "#{@city}," %>
                </td>
              </tr>
              <tr>
                <td>Zip</td>
                <td>

                  <%= "#{@zipcode}." %>
                </td>
              </tr>
              <tr>
                <td>Value</td>
                <td>
                  <% if @value  %>
                  <%= "#{@apartment.parse_value(@value)}" %>
                  <% if @trending %>
                    <i class="arrow up icon" style="margin-left:10px;color:#9ACD32"></i>
                  <% else %>
                    <i class="arrow down icon" style="margin-left:10px;color:red"></i>
                  <% end %>
                <% else %>
                  Price On Request
                <% end %>
              </td>
              </tr>
              <tr>
                <td>Details</td>
                <td>
                  <%= "#{@bedrooms} Bed : #{@bathrooms} Bath : #{@sqft} sqft" %>
              </td>
              </tr>


          </table>
          </div>
      </div>

      <div class="eight wide column" style="border-radius:.28571429rem;" >
        <div class="flex-container">

        <div class="slideshow-container" style="max-width:100%;max-height:100%;border-radius:.28571429rem;">
            <div>
              <% i = 0 %>
              <% while i < @images.length %>
              <div class="mySlides fade" >
                <div class="numbertext"><%= i + 1 %> / <%= @images.count %></div>
                <img src="<%= @images[i] %>" style="width:100%;border-radius:.28571429rem;">
              </div>
              <% i += 1 %>
              <% end %>
              <% if @images[0] != "https://www.gumtree.com/static/1/resources/assets/rwd/images/orphans/a37b37d99e7cef805f354d47.noimage_thumbnail.png" %>
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" style="margin-right:100px" onclick="plusSlides(1)">&#10095;</a>
              <% end %>
            </div>
          </div>
        </div>
        <br>

      </div>
    </div>
    <br>

    <div class="ui divider"></div>
    <div class="ui grid">
      <div class="four wide column">
        <%= link_to "Save Listing", user_apartments_path(apartment_id: @apartment.id), method: :post, class:"ui button primary" %>
      </div>
      <div class="eight wide column">
        <% if flash[:notice] %>
          <div class="ui message">
            <div class="header">
              <%= flash[:notice] %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="four wide column">
        <div class="" style="float:right">
          <% if Apartment.find_by(id: (@apartment.id - 1)) && Apartment.find_by(id: (@apartment.id + 1))%>
            <%= link_to "Prev", apartment_path(@apartment.id - 1), class:"ui button primary" %>
            <%= link_to "Next", apartment_path(@apartment.id + 1), class:"ui button primary" %>
          <% elsif Apartment.find_by(id: (@apartment.id - 1)) %>
            <%= link_to "Prev", apartment_path(@apartment.id - 1), class:"ui button primary" %>
            <button type="button" name="button" class="ui button primary" style="color:white">Next</button>
          <% elsif Apartment.find_by(id: (@apartment.id + 1)) %>
            <button type="button" name="button" class="ui button primary" style="color:white">Prev</button>
            <%= link_to "Next", apartment_path(@apartment.id + 1), class:"ui button primary" %>
          <% end %>
        </div>
      </div>
    </div>

    <script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
      showSlides(slideIndex += n);
    }

    function currentSlide(n) {
      showSlides(slideIndex = n);
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";
      dots[slideIndex-1].className += " active";
    }
    </script>

  </body>
</html>